{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "restart-operator.fullname" . }}
  labels:
    {{- include "restart-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-4"
rules:
  # Allow managing restart schedules
  - apiGroups: ["restart-operator.k8s"]
    resources: ["restartschedules"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Allow managing status subresource
  - apiGroups: ["restart-operator.k8s"]
    resources: ["restartschedules/status"]
    verbs: ["get", "update", "patch"]
  
  # Allow managing workloads that need to be restarted
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch", "update", "patch"]
  
  # For leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update", "list", "watch"]
  
  # For event publishing
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]

---
# Cluster role binding for all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "restart-operator.fullname" . }}
  labels:
    {{- include "restart-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "restart-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "restart-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
# Leader election role binding in operator namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "restart-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "restart-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "-2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "restart-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "restart-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}